sudo: false
language: minimal

addons:
  apt:
    packages:
    - luarocks

git:
  submodules: false

install:
  - luarocks install --local luacheck

before_script:
  - /home/travis/.luarocks/bin/luacheck . --no-color -q

script:
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    - /^v\d+\.\d+\.\d+(-\S*)?$/